mongodb:
    host_list: ["10.100.2.9"]
    port: 27017
board_list: ["4820","50","4540","4482","5287","5285","4389","4880","4821"]

supply_prefix_name: "supply"
supply_save_path: "/data1/ad/data/etl"
supply_key_list: ["sid","boardid","deviceid","voideoid","slotid","cardid","creativeid","intime","p_c_os","p_c_type","p_c_ip","p_v_hid","p_v_rid","p_v_rname"]
supply_value_type: ["str", "int", "str", "int", "list_int", "list_int", "list_int", "int", "str", "int", "str", "int", "int", "str"]
supply_value_isnull: [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1]

demand_prefix_name: "demand"
demand_save_path: "/data1/ad/data/etl"
demand_key_list: ["sid","boardid","deviceid","voideoid","slotid","cardid","creativeid","intime","type","ip","second","orderid"]
demand_value_type: ["str", "int", "str", "int", "int", "int", "int", "int", "int", "str", "int", "int"]
demand_value_isnull: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

metrics:
    reqs: 
        hour: 'Reqs_Facts_By_Hour'
        day: 'Reqs_Facts_By_Day'
    code_serves:
        hour: 'Hit_Facts_By_Hour'
        day: 'Hit_Facts_By_Day'
    #impressions:
    #    hour: 'Impressions_facts_by_hour'
    #    day: 'impressions_facts_by_day'
    #click:
    #    hour: 'Ad_facts_by_hour'
    #    day: 'Ad_facts_by_day'
    

log_config_path: "logger.conf"

boardid_dict:
    '4820': ['65', '66', '67', '68', '69']
    '50': ['84', '85', '86', '87', '88']
    '4540': ['89', '90', '91', '92', '93', '94', '95', '107']
    '4482': ['96', '97', '98', '99', '100', '101', '108']
    '5287': ['102', '103', '104', '105', '106']
    '5285': ['132', '122', '121', '120', '119', '118', '117', '116', '115', '114', '113', '112', '111', '110']
    '4389': ['109']
    '4880': ['102815', '102813']
    '4821': ['127']
    '5286': ['134', '135', '136']
database:
    db_name: 'adc'
    user: 'postgres'
    password: 'adpg@150909'
    host: '10.100.5.80'
    port: '11921'
