file_split: ","
ad_split: ","
output_column_sep: "\t"
strip_char: \"
adlist_split: "|"
with_header: True
batch_write_size: 100000
slotid: slot_id
mediabuyid: mediabuy_id
creativeid: creator_id
ip: ip
server_timestamp: server_timestamp
ad_list: ad_list
ipb_filepath: util/IPB.csv
city_filepath: util/city_province.csv
