file_split: "\t"
ad_split: ","
adlist_split: "|"
batch_write_size: 100000
header: ['ip','ad_event_type','url','video_id','playlist_id','board_id','request_res','ad_list','time_delay','request_str','slot_id','mediabuy_id','creator_id','video_play_time','order','play_event','pf','device_id','uid','net','os','manufacturer','model','app','timestamp','server_timestamp','session_id','tag']             #原日志文件header（追加了tag的）
flat_header: ['ip','ad_event_type','url','video_id','playlist_id','board_id','request_res','ad_list','time_delay','request_str','slot_id','mediabuy_id','creator_id','video_play_time','order','play_event','pf','device_id','uid','net','os','manufacturer','model','app','timestamp','server_timestamp','session_id','tag','province','city','seq','group_id']#最终打平文件的header
slotid: slot_id
mediabuyid: mediabuy_id
creativeid: creator_id
ip: ip
server_timestamp: server_timestamp
ad_list: ad_list
ipb_filepath: util/IPB.csv
city_filepath: util/city_province.csv
