current_env: release

beta: #测试环境
    monitor: 
        ##########common config########################
        audit_header: ['ip','ad_event_type','url','video_id','playlist_id','board_id','request_res','ad_list','time_delay','request_str','slot_id','mediabuy_id','creator_id','video_play_time','order','play_event','pf','device_id','uid','net','os','manufacturer','model','app','timestamp','server_timestamp','session_id','tag']
        header: ['ip','ad_event_type','url','video_id','playlist_id','board_id','request_res','ad_list','time_delay','request_str','slot_id','mediabuy_id','creator_id','video_play_time','order','play_event','pf','device_id','uid','net','os','manufacturer','model','app','timestamp','server_timestamp','session_id','tag','province','city','seq','group_id']
        input_column_sep: "\t"
        output_column_sep: "\t"
        na_rep: " "
        bearychat_channel: "广告-数据"
        ##########petl config##########################
        with_header: True
        chance_aggre_header: ['board_id','slot_id','pf']
        count_aggre_header: ['board_id','slot_id','pf']
        seq_aggre_header: ['seq','board_id','group_id','pf']
        up_aggre_header: ['board_id','realslotid','pf']
        start_aggre_header: ['board_id','slot_id','mediabuy_id','creator_id','pf']
        end_aggre_header: ['board_id','slot_id','mediabuy_id','creator_id','pf']
        click_aggre_header: ['board_id','slot_id','mediabuy_id','creator_id','pf']
        aggre_header: ['slot_id','mediabuy_id','creator_id']
        chance_select: "{ad_event_type} == 'e' and ({request_res} == '0' or {request_res}== '1') and  {tag} < 100 "
        count_select: "{ad_event_type} == 'e'  and {tag} < 100"
        up_select: "{ad_event_type} == 'e' and {tag} < 100 "
        seq_select: "{ad_event_type} == 'e' and {request_res} == '0' and {tag} < 100 and {seq} != '-1'"
        start_select: "{ad_event_type} == 'p' and {play_event} == 's' and {tag} < 100 "
        end_select: "{ad_event_type} == 'p' and {play_event} == 'e'  and {tag} < 100 "
        click_select: "{ad_event_type} == 'p' and {play_event} == 'c' and {tag} < 100 "
        common_select:
        batch_read_size: 100000
        display_pos: display_poss
        display: display
        display_sale: display_sale
        impression: impression
        impression_end: impression_end
        click: click
        up: up
        ad_list: ad_list
        slotid: slot_id
        mediabuyid: mediabuy_id
        creativeid: creator_id
        player_id: board_id
        group_id: group_id      #group_id 对应header中名称
        seq: seq                # seq 对应header中的名称
        tag: tag
        addslotid: realslotid   # 添加的列名称
        ##########pandas config##########################
        header_type: {
            'ip':'string',
            'ad_event_type':'string',
            'province':'string',
            'city':'string',
            'url':'string',
            'video_id':'string',
            'playlist_id':'string',
            'board_id':'string',
            'request_res':'string',
            'ad_list':'list',
            'time_delay':'string',
            'request_str':'string',
            'slot_id':'string',
            'query-slot_id':'string',
            'mediabuy_id':'string',
            'creator_id':'string',
            'video_play_time':'string',
            'order':'string',
            'group_id':'string',
            'play_event':'string',
            'pf':'string',
            'device_id':'string',
            'uid':'string',
            'net':'string',
            'os':'string',
            'manufacturer':'string',
            'model':'string',
            'app':'string',
            'timestamp':'string',
            'server_timestamp':'string',
            'session_id':'string',
            'seq':'string',
            'tag':'int',
            'total':'int'
        }
        read_csv_chunk: 500000
        db_commit_chunk: 10000
        algorithm: 
            display_poss: #广告位展示机会
                group_item: ['board_id','pf','query-slot_id']
                condition:
                    query-slot-count: {
                        filter: [
                            ['ad_event_type','==','e'],
                            ['request_res','in',['0','1']],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            display_sale: #售卖展示数
                group_item: ['board_id','pf','slot_id']
                condition:
                    count: {
                        filter: [
                            ['ad_event_type','==','e'],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            display: #广告次序实际展示数
                group_item: ['board_id','pf','seq','group_id']
                condition:
                    'count': {
                        filter: [
                            ['ad_event_type','==','e'],
                            ['request_res','==','0'],
                            ['tag','<',100],
                            ['seq','!=','-1']
                        ],
                        output_name: 'total'
                    }
            impression: #成功播放数
                group_item: ['board_id','slot_id','mediabuy_id','creator_id','pf'] #广告位ID，投放ID，创意ID
                condition:
                    count: {
                        filter: [
                            ['ad_event_type','==','p'],
                            ['play_event','==','s'],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            impression_end: #播放完成数
                group_item: ['board_id','slot_id','mediabuy_id','creator_id','pf'] #广告位ID，投放ID，创意ID
                condition:
                    count: {
                        filter: [
                            ['ad_event_type','==','p'],
                            ['play_event','==','e'],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            click: #广告点击数
                group_item: ['board_id','slot_id','mediabuy_id','creator_id','pf'] #广告位ID，投放ID，创意ID
                condition:
                    count: {
                        filter: [
                            ['ad_event_type','==','p'],
                            ['play_event','==','c'],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            up: #升位数
                group_item: ['board_id','query-slot_id','pf'] #播放器ID、广告位ID
                condition: 
                    query-slot-compare: {
                        filter: [
                            ['ad_event_type','==','e'], 
                            ['request_res','in',['0','1']],
                            ['tag','<',100],
                            ['seq','!=','-1']
                        ],
                        output_name: 'total'
                    }

release: #生产环境
    monitor: 
        ##########common config########################
        audit_header: ['ip','ad_event_type','url','video_id','playlist_id','board_id','request_res','ad_list','time_delay','request_str','slot_id','mediabuy_id','creator_id','video_play_time','order','play_event','pf','device_id','uid','net','os','manufacturer','model','app','timestamp','server_timestamp','session_id','tag']
        header: ['ip','ad_event_type','url','video_id','playlist_id','board_id','request_res','ad_list','time_delay','request_str','slot_id','mediabuy_id','creator_id','video_play_time','order','play_event','pf','device_id','uid','net','os','manufacturer','model','app','timestamp','server_timestamp','session_id','tag','province','city','seq','group_id']
        input_column_sep: "\t"
        output_column_sep: "\t"
        na_rep: " "
        bearychat_channel: "广告-数据系统报告"
        ##########petl config##########################
        with_header: True
        chance_aggre_header: ['board_id','slot_id','pf']
        count_aggre_header: ['board_id','slot_id','pf']
        seq_aggre_header: ['seq','board_id','group_id','pf']
        up_aggre_header: ['board_id','realslotid','pf']
        start_aggre_header: ['board_id','slot_id','mediabuy_id','creator_id','pf']
        end_aggre_header: ['board_id','slot_id','mediabuy_id','creator_id','pf']
        click_aggre_header: ['board_id','slot_id','mediabuy_id','creator_id','pf']
        aggre_header: ['slot_id','mediabuy_id','creator_id']
        chance_select: "{ad_event_type} == 'e' and ({request_res} == '0' or {request_res}== '1') and  {tag} < 100 "
        count_select: "{ad_event_type} == 'e'  and {tag} < 100"
        up_select: "{ad_event_type} == 'e' and {tag} < 100 "
        seq_select: "{ad_event_type} == 'e' and {request_res} == '0' and {tag} < 100 and {seq} != '-1'"
        start_select: "{ad_event_type} == 'p' and {play_event} == 's' and {tag} < 100 "
        end_select: "{ad_event_type} == 'p' and {play_event} == 'e'  and {tag} < 100 "
        click_select: "{ad_event_type} == 'p' and {play_event} == 'c' and {tag} < 100 "
        common_select:
        batch_read_size: 100000
        display_pos: display_poss
        display: display
        display_sale: display_sale
        impression: impression
        impression_end: impression_end
        click: click
        up: up
        ad_list: ad_list
        slotid: slot_id
        mediabuyid: mediabuy_id
        creativeid: creator_id
        player_id: board_id
        group_id: group_id      #group_id 对应header中名称
        seq: seq                # seq 对应header中的名称
        tag: tag
        addslotid: realslotid   # 添加的列名称
        ##########pandas config##########################
        header_type: {
            'ip':'string',
            'ad_event_type':'string',
            'province':'string',
            'city':'string',
            'url':'string',
            'video_id':'string',
            'playlist_id':'string',
            'board_id':'string',
            'request_res':'string',
            'ad_list':'list',
            'time_delay':'string',
            'request_str':'string',
            'slot_id':'string',
            'query-slot_id':'string',
            'mediabuy_id':'string',
            'creator_id':'string',
            'video_play_time':'string',
            'order':'string',
            'group_id':'string',
            'play_event':'string',
            'pf':'string',
            'device_id':'string',
            'uid':'string',
            'net':'string',
            'os':'string',
            'manufacturer':'string',
            'model':'string',
            'app':'string',
            'timestamp':'string',
            'server_timestamp':'string',
            'session_id':'string',
            'seq':'string',
            'tag':'int',
            'total':'int'
        }
        read_csv_chunk: 10000000
        db_commit_chunk: 10000
        algorithm: 
            display_poss: #广告位展示机会
                group_item: ['board_id','pf','query-slot_id']
                condition:
                    query-slot-count: {
                        filter: [
                            ['ad_event_type','==','e'],
                            ['request_res','in',['0','1']],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            display_sale: #售卖展示数
                group_item: ['board_id','pf','slot_id']
                condition:
                    count: {
                        filter: [
                            ['ad_event_type','==','e'],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            display: #广告次序实际展示数
                group_item: ['board_id','pf','seq','group_id']
                condition:
                    'count': {
                        filter: [
                            ['ad_event_type','==','e'],
                            ['request_res','==','0'],
                            ['tag','<',100],
                            ['seq','!=','-1']
                        ],
                        output_name: 'total'
                    }
            impression: #成功播放数
                group_item: ['board_id','slot_id','mediabuy_id','creator_id','pf'] #广告位ID，投放ID，创意ID
                condition:
                    count: {
                        filter: [
                            ['ad_event_type','==','p'],
                            ['play_event','==','s'],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            impression_end: #播放完成数
                group_item: ['board_id','slot_id','mediabuy_id','creator_id','pf'] #广告位ID，投放ID，创意ID
                condition:
                    count: {
                        filter: [
                            ['ad_event_type','==','p'],
                            ['play_event','==','e'],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            click: #广告点击数
                group_item: ['board_id','slot_id','mediabuy_id','creator_id','pf'] #广告位ID，投放ID，创意ID
                condition:
                    count: {
                        filter: [
                            ['ad_event_type','==','p'],
                            ['play_event','==','c'],
                            ['tag','<',100]
                        ],
                        output_name: 'total'
                    }
            up: #升位数
                group_item: ['board_id','query-slot_id','pf'] #播放器ID、广告位ID
                condition: 
                    query-slot-compare: {
                        filter: [
                            ['ad_event_type','==','e'], 
                            ['request_res','in',['0','1']],
                            ['tag','<',100],
                            ['seq','!=','-1']
                        ],
                        output_name: 'total'
                    }

