column_sep: "\t"
output_column_sep: ","
supply:
    raw_header: ['boardid','deviceid','videoid','slotid','cardid','creativeid','p_v_hid','p_v_rid','p_v_rname','p_c_type',
                'p_c_ip','cityid','intime','p_c_idfa1','p_c_imei','p_c_ctmid','p_c_mac','p_c_anid','p_c_openudid','p_c_idfa',
                'p_c_odin','p_c_aaid','p_c_duid','sid']
    agg_header: ['slotid', 'cardid', 'creativeid']
demand:
    raw_header: []
    agg_header: []
database:
    db_name: adc
    user: postgres
    password: 
    host: 10.100.5.80
    port: 11921
db_table:
    ad_facts_by_hour:
         cols: "ad_slot_id,ad_card_id,ad_campaign_id,ad_creative_id,click,impressions_start_total,impressions_finish_total,date_id,time_id"
    hit_facts_by_hour:
        cols: "ad_slot_id,ad_card_id,ad_creative_id,ad_campaign_id,os,total,date_id,time_id"
    reqs_facts_by_hour:
        cols: "ad_slot_id,ad_campaign_id,os,total,date_id,time_id"
